from tkinter import *
root=Tk()
root.title("Temperature Converter")
root.geometry("450x300")
root.resizable(False, False)
title_label=Label(root, text="TEMPERATURE CONVERTER",fg='#800000', font=('Arial', 20, "bold"))
title_label.pack(pady=20)
frame1=Frame(root)
frame1.pack()
frame2=Frame(root)
frame2.pack()
e1=Entry(frame1,highlightthickness=1,highlightbackground = "black")
e2=Entry(frame2,highlightthickness=1,highlightbackground = "black")
t1=Text(frame1,state="disabled",width=15,height=0,highlightthickness=1,highlightbackground = "black")
t2=Text(frame2,state="disabled",width=15,height=0,highlightthickness=1,highlightbackground = "black")
def bac_c():
    frame1.pack()
    b1.pack(pady=10)
    frame2.pack()
    b2.pack(pady=10)
    label1.pack_forget()
    e1.pack_forget()
    label2.pack_forget()
    t1.pack_forget()
    convert.pack_forget()
    back.pack_forget()
def bac_f():
    frame1.pack()
    b1.pack(pady=10)
    frame2.pack()
    b2.pack(pady=10)
    label1.pack_forget()
    e2.pack_forget()
    label2.pack_forget()
    t2.pack_forget()
    convert.pack_forget()
    back.pack_forget()
def c_f():
    c = int(e1.get())
    f = ((c*9)/(5))+32
    t1.config(state='normal')
    t1.delete('1.0',END)
    t1.insert(END,f)
    t1.config(state='disabled')
def f_c():
    f = int(e2.get())
    c = (f-32)*5/9
    t2.config(state='normal')
    t2.delete('1.0',END)
    t2.insert(END,round(c,3))
    t2.config(state='disabled')
def win1():
    frame2.pack_forget()
    b1.pack_forget()
def win2():
    frame1.pack_forget()
    b2.pack_forget() 

def f1():
    global label1, label2, convert, back
    label1=Label(frame1, text="Enter Temperature in Celsius",font=('Arial', 10,"bold"))
    label1.pack()
    e1.pack(pady=10)
    label2=Label(frame1, text="Temperature In Fahrenheit:",font=('Arial', 10,"bold"))
    label2.pack(pady=10)
    t1.pack()
    convert=Button(frame1, text="Convert",width=10,background='black',fg='white', font=('Arial', 10), command=lambda:c_f())
    convert.pack(pady=10)
    back=Button(frame1, text="Back", width=10,background='#800000',fg='white',font=('Arial', 10), command=lambda:bac_c())
    back.pack()
def f2():
    global label1, label2, convert, back
    label1=Label(frame2, text="Enter Temperature in Fahrenheit",font=('Arial', 10,"bold"))
    label1.pack()
    e2.pack(pady=10)
    label2=Label(frame2, text="Temperature In Celsius:",font=('Arial', 10,"bold"))
    label2.pack(pady=10)
    t2.pack()
    convert=Button(frame2, text="Convert",width=10,background='black',fg='white',font=('Arial', 10), command=lambda:f_c())
    convert.pack(pady=10)
    back=Button(frame2, text="Back",width=10, background='#800000',fg='white',font=('Arial', 10), command=lambda:bac_f())
    back.pack()
    

b1=Button(frame1, text="Celsius to Fahrenheit",background='white',font=('Arial', 15), command=lambda:[win1(), f1()])
b2=Button(frame2, text="Fahrenheit to Celsius", background='white',font=('Arial', 15), command=lambda:[win2(), f2()])
b1.pack(pady=10)
b2.pack(pady=10)
root.mainloop()